name: Run test with ci/cd

on:
    pull reequest:
     branches:
      - main
    push:
     branches:
      - main
jobs:
    run_api_automation:
     runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3

     - name: Set up python
       usess: actions/setup-python@v3
       with:
        python-version: '3.x'

     - name:Install dependencies
     - run:
        python -n pip install --upgrade pip
        pip install -r requirments.txt

     - name: Run tesst with pytest
       run: pytest test/ -v
       env:
         WEBHOOK_SLACK: ${{ secretss.WEBHOOK_SLACK }}
         TOKEN_QASE_IO: ${{ secretss.TOKEN_QASE_IO }}



     - name: Send Report Slack
       run: python setting/slack_notification.py
       env:
         WEBHOOK_SLACK: ${{ secretss.WEBHOOK_SLACK }}